"""
Compliance verdict data models.

Defines the output of Node 3 (Assertion Evaluator) — per-obligation, per-broker
compliance verdicts with full evidence trails.

These feed into Node 4 (Scoreboard Generator).
"""

from datetime import datetime
from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


class VerdictStatus(str, Enum):
    """Final compliance status for a single obligation-broker pair.

    COMPLIANT:   All required events occurred within deadlines.
    NON_COMPLIANT: Deadlines elapsed without required events.
    PENDING:     Evaluation incomplete — relevant events not yet received.
    """

    COMPLIANT = "compliant"
    NON_COMPLIANT = "non_compliant"
    PENDING = "pending"


class ComplianceVerdict(BaseModel):
    """Deterministic compliance verdict for one obligation evaluated against one broker.

    Generated by Node 3 (Evaluator) — must NEVER involve an LLM.
    Every verdict is traceable back to the originating obligation, FSM, and events.
    """

    verdict_id: str = Field(
        default_factory=lambda: f"VER-{uuid4().hex[:12].upper()}",
        description="Unique verdict identifier",
    )
    obligation_ref: str = Field(
        ...,
        description="References the source ObligationClause.clause_id",
    )
    broker_id: str = Field(
        ...,
        description="Broker this verdict applies to",
    )
    fsm_ref: str = Field(
        ...,
        description="References the HybridFSM.fsm_id used for evaluation",
    )
    status: VerdictStatus = Field(
        ...,
        description="Final compliance status after evaluation",
    )
    current_state: str = Field(
        ...,
        min_length=1,
        description="Terminal state of the FSM after processing all events",
    )
    evidence: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Evidence trail supporting this verdict. Includes:\n"
            "  - matched_events: list of (event_id, transition, timestamp) tuples\n"
            "  - timeline_status: computed deadline info (start_time, deadline, elapsed)\n"
            "  - transition_log: ordered list of state transitions executed"
        ),
    )
    evaluated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when the evaluation was performed",
    )

    @property
    def is_final(self) -> bool:
        """A verdict is final if it's not PENDING."""
        return self.status != VerdictStatus.PENDING
